<?php
/**
 * Created by PhpStorm.
 * User: binh
 * Date: 29/09/2015
 * Time: 11:22
 */

/**
 * Implement hook_field_schema()
 */
function payment_term_field_schema($field) {
    if($field['type'] == 'payment_term') {
        $columns = array(
            'value' => array(
                'type' => 'int',
                'not null' => FALSE,
                'description' => '',
            ),
        );
    }
    return array(
        'columns' => $columns,
    );
}