<?php
/**
 * Created by PhpStorm.
 * User: binh
 * Date: 29/09/2015
 * Time: 23:08
 */

/**
 * Implement hook_form_alter()
 */
function ic_contact_email_form_alter(&$form, &$form_state, $form_id) {
    if($form_id == 'commerce_order_ui_order_form') {
        $form['user']['name']['#ajax'] = array(
            'callback' => 'ic_contact_email_callback',
            'wrapper' => 'autocomplete-by-user-name-ajax-replace',
        );
        $form['user']['mail']['#prefix'] = '<div id="autocomplete-by-user-name-ajax-replace">';
        $form['user']['mail']['#suffix'] = '</div>';
    }
    if(!empty($form_state['values']['name'])) {
        $users = entity_load('user');
        foreach($users as $key => $user) {
            if($form_state['values']['name'] == $user->name) {
                $result = $user->mail;
            }
        }
        $form['user']['mail']['#value'] = $result;
        $form['user']['mail']['#disabled'] = TRUE;
    }
}
function ic_contact_email_callback($form, $form_state) {
    return $form['user']['mail'];
}